language: python
python:
  - "3.6"
  - "3.7-dev"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - cd src
script:
  - coverage run --source . -m pytest ../tests/
after_success:
  - coveralls
